// Code generated by goctl. DO NOT EDIT.
package types

type ChatRecordAddReq struct {
	Title      string `json:"title"`
	ChatRecord string `json:"chatRecord"`
	UserName   string `json:"userName,optional"`
}

type ChatRecordAddResp struct {
	Success string `json:"success"`
	Errcode string `json:"errorCode"`
	ErrMsg  string `json:"errorMessage"`
}

type ChatRecordDelReq struct {
	Id string `json:"id"`
}

type ChatRecordDelResp struct {
	Success string `json:"success"`
	Errcode string `json:"errorCode"`
	ErrMsg  string `json:"errorMessage"`
}

type ChatRecordInfo struct {
	Id         string `json:"id"`
	Title      string `json:"title"`
	ChatRecord string `json:"chatRecord"`
	UserName   string `json:"userName"`
	CreateBy   string `json:"createBy,optional"`
	UpdateBy   string `json:"updateBy,optional"`
	CreatedAt  string `json:"createdAt,optional"`
	UpdatedAt  string `json:"updatedAt,optional"`
}

type ChatRecordListReq struct {
	Title string `json:"title,optional"`
	Page  int    `json:"page"`
	Limit int    `json:"limit"`
}

type ChatRecordListResp struct {
	Success  string           `json:"success"`
	Errcode  string           `json:"errorCode"`
	ErrMsg   string           `json:"errorMessage"`
	Data     []ChatRecordInfo `json:"data"`
	Current  int              `json:"current"`
	PageSize int              `json:"pageSize"`
	Total    int              `json:"total"`
}

type ChatRecordUpdateReq struct {
	AuthKey string `json:"authKey"`
	ChatRecordInfo
}

type ChatRecordUpdateResp struct {
	Success string `json:"success"`
	Errcode string `json:"errorCode"`
	ErrMsg  string `json:"errorMessage"`
}
